update `TestCase.run()` to receive a `result`
Checklist:
- Invoke tearDown even if the test method fails
- Run multiple tests 👈🏼

---

Output:
➜ python3 src/test_case_test.py
Traceback (most recent call last):
  File "tdd-xunit-example/src/test_case_test.py", line 39, in <module>
    print(TestCaseTest("testTemplateMethod").run().summary())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TestCase.run() missing 1 required positional argument: 'result'