introduce `WasRun` class
Checklist:
- Invoke test method 👈🏼
- Invoke setUp first
- Invoke tearDown afterward
- Invoke tearDown even if the test method fails
- Run multiple tests
- Report collected results

---

Output:
➜ python3 src/index.py
Traceback (most recent call last):
  File "tdd-xunit-example/src/index.py", line 3, in <module>
    test = WasRun("testMethod")
           ^^^^^^^^^^^^^^^^^^^^
TypeError: WasRun() takes no arguments