update implementation to call `run()` instead of `testMethod()` directly
Checklist:
- Invoke test method 👈🏼
- Invoke setUp first
- Invoke tearDown afterward
- Invoke tearDown even if the test method fails
- Run multiple tests
- Report collected results

---

Output:
➜ python3 src/index.py
None
Traceback (most recent call last):
  File "tdd-xunit-example/src/index.py", line 5, in <module>
    test.run()
    ^^^^^^^^
AttributeError: 'WasRun' object has no attribute 'run'