introduce a `TestResult` class with hardcoded impl
This class will be used to hold a summary of the test suite execution. For now, though, it's just implementing a summary method with a hardcoded implementation.

Checklist:
- Invoke tearDown even if the test method fails
- Run multiple tests
- Report collected results 👈🏼

---

Output:
➜ python3 src/test_case_test.py
Traceback (most recent call last):
  File "tdd-xunit-example/src/test_case_test.py", line 12, in <module>
    TestCaseTest("testTemplateMethod").run()
  File "tdd-xunit-example/src/test_case.py", line 12, in run
    method()
  File "tdd-xunit-example/src/test_case_test.py", line 9, in testTemplateMethod
    assert ("1 run, 0 failed" == result.summary())
                                 ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'summary'